#pragma config(Sensor, S1,     UltrasonicSensor, sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          Arm,           tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          LeftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          RightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int MaxDistance = 30;
bool boolTurnedRight = false;
bool boolTurnedLeft = false;
bool boolTurnedFront = true;

void ResetAllMotorEncoders()
{
	resetMotorEncoder(Arm);
	resetMotorEncoder(LeftMotor);
	resetMotorEncoder(RightMotor);
}

void ResetSensorLocation()
{
	motor[Arm] = -50;
	sleep(1000);
	motor[Arm] = 0;
	ResetAllMotorEncoders();
	displayBigTextLine(10, "Let's face front!");
	setMotorTarget(Arm, 105, 15);
	while(getMotorRunning(Arm))
	{
		//do nothing
	}
}

task main()
{
	ResetSensorLocation();
	while(true)
	{
		ResetAllMotorEncoders();
		GetSensorReading();
		if(getUSDistance(UltrasonicSensor) < MaxDistance)
		{
			sleep(5000);
			setMotorSyncEncoder(LeftMotor, RightMotor, 0, 360, 60);
		}
	}
}
