#pragma config(Sensor, S1,     UltrasonicSensor, sensorEV3_Ultrasonic, modeEV3Ultrasonic_Inch)
#pragma config(Motor,  motorA,          Arm,           tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          LeftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          RightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int MaxDistance = 12;

void ResetAllMotorEncoders()
{
	resetMotorEncoder(Arm);
	resetMotorEncoder(LeftMotor);
	resetMotorEncoder(RightMotor);
}

task main()
{
	while(true)
	{
		ResetAllMotorEncoders();
		setMotorTarget(Arm, -90, 15);
	}

}
