#pragma config(Sensor, S1,     ColorSensor,    sensorEV3_Color)
#pragma config(Sensor, S3,     LightSensor,    sensorLightActive)
#pragma config(Motor,  motorB,          LeftTire,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          RightTire,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int KSoundVolume = 5;
int KForwardSpeed = 60;
int KForwardRotate = 720;
int KForwardRatio = 0;
int KDebugTimeout = 5000;
const int KTrayLength = 7;
const int KTrayWidth = 5;

int KushalTray[KTrayLength][KTrayWidth];

void PrintStats()
{
	displayBigTextLine(4, "welcome, kus");
	short lightSensorValue;
	lightSensorValue = SensorValue(LightSensor);
	displayBigTextLine(6, "%d", lightSensorValue);
	float colorSensorValue;
	colorSensorValue = getColorReflected(ColorSensor);
	displayBigTextLine(8, "%d", colorSensorValue);
	resetMotorEncoder(LeftTire);
	resetMotorEncoder(RightTire);
	sleep(KDebugTimeout);
}

void InitializeTray(int InitialValue)
{
	for (int i = 0; i < KTrayLength; i++)
	{
		for (int j = 0; j < KTrayWidth; j++)
		{
			KushalTray[i][j] = InitialValue;
		}
	}
}

void GoForward()
{
	sleep(KDebugTimeout);
	setMotorSyncEncoder(LeftTire, RightTire, KForwardRatio, KForwardRotate, KForwardSpeed);
}

bool ShouldGoLeft()
{
	if(SensorValue(LightSensor) > 30 && SensorValue(ColorSensor) < 5){return true;} else {return false;}
}

bool ShouldGoRight()
{
	if(SensorValue(LightSensor) < 30 && SensorValue(ColorSensor) > 5){return true;} else {return false;}
}

task main()
{
	setSoundVolume(KSoundVolume);
	InitializeTray(0);
	while(true)
	{
		PrintStats();
		if(ShouldGoLeft())
		{
			displayBigTextLine(10, "go left");
		}
		if(ShouldGoRight())
		{
			displayBigTextLine(10, "go right");
		}
		if(!ShouldGoRight() && !ShouldGoLeft())
		{
			displayBigTextLine(10, "go straight");
			GoForward();
		}
	}
}
