#pragma config(Sensor, S2,     LeftColor,      sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S1,     RightColor,     sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S3,     Gyro,           sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S4,     Touch,          sensorEV3_Touch)
#pragma config(Motor,  motorB,          LeftTire,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          RightTire,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
const int kushal_length = 7;
const int kushal_width = 5;
const int kushal_production_sleep_time = 100;
struct kushal_block{
	bool kushal_block_is_red;
}
struct kushal_structure{
	kushal_block kushal_structure_array[kushal_length][kushal_width];
}
task main()
{
	sleep(kushal_production_sleep_time);
	resetGyro(Gyro);
	sleep(kushal_production_sleep_time);
	kushal_structure ks;
	for (int i = 0; i < kushal_length; i++)
	{
		for (int j = 0; j < kushal_width; j++)
		{
			ks.kushal_structure_array[i][j].kushal_block_is_red = false;
		}
	}
}
