#pragma config(Motor,  motorA,          LeftTire,      tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorD,          RightTire,     tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int KSoundVolume = 5;

int ForwardSpeed = 60;

void KnightRiderOne()
{
  //        125 = Tempo
  //          5 = Default octave
  //    Quarter = Default note length
  //        10% = Break between notes
  //
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(    0,   11); wait1Msec( 120);  // Note(Rest, Duration(16th))
  playTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(    0,   11); wait1Msec( 120);  // Note(Rest, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(  622,   11); wait1Msec( 120);  // Note(D#, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(    0,   11); wait1Msec( 120);  // Note(Rest, Duration(16th))
  playTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(    0,   11); wait1Msec( 120);  // Note(Rest, Duration(16th))
  playTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(  698,   11); wait1Msec( 120);  // Note(F, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(  622,   11); wait1Msec( 120);  // Note(D#, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(  587,   11); wait1Msec( 120);  // Note(D, Duration(16th))
  playTone(    0,   11); wait1Msec( 120);  // Note(Rest, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(  587,   11); wait1Msec( 120);  // Note(D, Duration(16th))
  playTone(  587,   11); wait1Msec( 120);  // Note(D, Duration(16th))
  playTone(    0,   11); wait1Msec( 120);  // Note(Rest, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(  587,   11); wait1Msec( 120);  // Note(D, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(  587,   11); wait1Msec( 120);  // Note(D, Duration(16th))
  playTone(  587,   11); wait1Msec( 120);  // Note(D, Duration(16th))
  playTone(  587,   11); wait1Msec( 120);  // Note(D, Duration(16th))
  playTone(  523,   11); wait1Msec( 120);  // Note(C, Duration(16th))
  playTone(  587,   11); wait1Msec( 120);  // Note(D, Duration(16th))
  playTone(  587,   11); wait1Msec( 120);  // Note(D, Duration(16th))
  playTone(  587,   11); wait1Msec( 120);  // Note(D, Duration(16th))
  playTone(  587,   11); wait1Msec( 120);  // Note(D, Duration(16th))
  playTone(    0,   11); wait1Msec( 120);  // Note(Rest, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(  587,   11); wait1Msec( 120);  // Note(D, Duration(16th))
  playTone(  587,   11); wait1Msec( 120);  // Note(D, Duration(16th))
  playTone(    0,   11); wait1Msec( 120);  // Note(Rest, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(  587,   11); wait1Msec( 120);  // Note(D, Duration(16th))
  playTone(  659,   11); wait1Msec( 120);  // Note(E, Duration(16th))
  playTone(  587,   11); wait1Msec( 120);  // Note(D, Duration(16th))
  playTone(  587,   11); wait1Msec( 120);  // Note(D, Duration(16th))
  playTone(  587,   11); wait1Msec( 120);  // Note(D, Duration(16th))
  playTone(  523,   11); wait1Msec( 120);  // Note(C, Duration(16th))
  playTone(  587,   11); wait1Msec( 120);  // Note(D, Duration(16th))
  playTone(  587,   11); wait1Msec( 120);  // Note(D, Duration(16th))
  playTone(  587,   11); wait1Msec( 120);  // Note(D, Duration(16th))
  return;
}

void KnightRiderTwo()
{
  //         63 = Tempo
  //          5 = Default octave
  //    Quarter = Default note length
  //        10% = Break between notes
  //
  playTone(  659,   21); wait1Msec( 238);  // Note(E, Duration(16th))
  playTone(  698,   11); wait1Msec( 119);  // Note(F, Duration(32th))
  playTone(  659,   11); wait1Msec( 119);  // Note(E, Duration(32th))
  playTone(  987,   43); wait1Msec( 476);  // Note(B, Duration(Eighth))
  playTone(  988,   21); wait1Msec( 238);  // Note(E6, Duration(16th))
  playTone( 1047,   11); wait1Msec( 119);  // Note(F6, Duration(32th))
  playTone(  988,   11); wait1Msec( 119);  // Note(E6, Duration(32th))
  playTone(  987,   43); wait1Msec( 476);  // Note(B, Duration(Eighth))
  playTone(  659,   21); wait1Msec( 238);  // Note(E, Duration(16th))
  playTone(  698,   11); wait1Msec( 119);  // Note(F, Duration(32th))
  playTone(  659,   11); wait1Msec( 119);  // Note(E, Duration(32th))
  playTone(  987,   21); wait1Msec( 238);  // Note(B, Duration(16th))
  playTone(  988,   21); wait1Msec( 238);  // Note(E6, Duration(16th))
  playTone(  880,   86); wait1Msec( 952);  // Note(D6)
  playTone(    0,   43); wait1Msec( 476);  // Note(Rest, Duration(Eighth))
  playTone(    0,   86); wait1Msec( 952);  // Note(Rest)
  playTone(  659,   21); wait1Msec( 238);  // Note(E, Duration(16th))
  playTone(  698,   11); wait1Msec( 119);  // Note(F, Duration(32th))
  playTone(  659,   11); wait1Msec( 119);  // Note(E, Duration(32th))
  playTone(  987,   43); wait1Msec( 476);  // Note(B, Duration(Eighth))
  playTone(  988,   21); wait1Msec( 238);  // Note(E6, Duration(16th))
  playTone( 1047,   11); wait1Msec( 119);  // Note(F6, Duration(32th))
  playTone(  988,   11); wait1Msec( 119);  // Note(E6, Duration(32th))
  playTone(  987,   43); wait1Msec( 476);  // Note(B, Duration(Eighth))
  playTone(  659,   21); wait1Msec( 238);  // Note(E, Duration(16th))
  playTone(  698,   11); wait1Msec( 119);  // Note(F, Duration(32th))
  playTone(  659,   11); wait1Msec( 119);  // Note(E, Duration(32th))
  playTone(  987,   21); wait1Msec( 238);  // Note(B, Duration(16th))
  playTone(  988,   21); wait1Msec( 238);  // Note(E6, Duration(16th))
  playTone( 1047,   86); wait1Msec( 952);  // Note(F6)
  playTone(    0,   86); wait1Msec( 952);  // Note(Rest)
  return;
}

void GoForward()
{
	setMotorSyncEncoder(LeftTire, RightTire, 0, 720, ForwardSpeed);
}

task main()
{
	setSoundVolume(KSoundVolume);
	KnightRiderOne();
	KnightRiderTwo();
	while(true)
	{
		GoForward();
	}
}
