#pragma config(Sensor, S2,     LeftColor,      sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S1,     RightColor,     sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S3,     Gyro,           sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S4,     Touch,          sensorEV3_Touch)
#pragma config(Motor,  motorB,          LeftTire,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          RightTire,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int current_x, current_y, final_x, final_y;

const int kushal_length = 7;
const int kushal_width = 5;
const int updownleftright = 4;
const int direction_counter_max = 50;
const int kushal_production_sleep_time = 2000;

bool have_we_visited_square[kushal_length][kushal_width];
int direction_counter;
char kushal_direction_array[direction_counter_max];

char lastDirection;

void kushal_follow_directions();

void set_kushal_direction_array_to_input()
{
	for (int i = 0; i < direction_counter_max; i++)
	{
		kushal_direction_array[i] = 'x';
	}
}

struct basic_square
{
	int x, y;
};

struct kushal_road{
	int start_x, start_y, end_x, end_y, distance;
};

struct kushal_square{
	kushal_road kushal_up, kushal_down, kushal_left, kushal_right;
	int location_x, location_y;
};

kushal_square kushal_board[kushal_length][kushal_width];

void Dijkstras(int s_x, int s_y, int e_x, int e_y)
{
	set_kushal_direction_array_to_input();
	bool done = false;
	int lowest, new_include_x, new_include_y, old_include_x, old_include_y;
	int kushal_distance_array[kushal_length][kushal_width];
	basic_square kushal_from_array[kushal_length][kushal_width];
	bool kushal_include[kushal_length][kushal_width];
	for (int i = 0; i < kushal_length; i++)
	{
		for (int j = 0; j < kushal_width; j++)
		{
			kushal_from_array[i][j].x = -1;
			kushal_from_array[i][j].y = -1;
			kushal_include[i][j] = false;
			kushal_distance_array[i][j] = 999;
		}
	}
	kushal_include[s_x][s_y] = true;
	kushal_distance_array[s_x][s_y] = 0;
	old_include_x = s_x;
	old_include_y = s_y;
	while(!done)
	{
		int x1 = kushal_board[old_include_x][old_include_y].kushal_up.end_x;
		int y1 = kushal_board[old_include_x][old_include_y].kushal_up.end_y;
		if (kushal_board[old_include_x][old_include_y].kushal_up.distance + kushal_distance_array[old_include_x][old_include_y] < kushal_distance_array[x1][y1])
		{
			kushal_distance_array[x1][y1] = kushal_board[old_include_x][old_include_y].kushal_up.distance + kushal_distance_array[old_include_x][old_include_y];
			kushal_from_array[x1][y1].x = old_include_x;
			kushal_from_array[x1][y1].y = old_include_y;
		}
		int x2 = kushal_board[old_include_x][old_include_y].kushal_down.end_x;
		int y2 = kushal_board[old_include_x][old_include_y].kushal_down.end_y;
		if (kushal_board[old_include_x][old_include_y].kushal_down.distance + kushal_distance_array[old_include_x][old_include_y] < kushal_distance_array[x2][y2])
		{
			kushal_distance_array[x2][y2] = kushal_board[old_include_x][old_include_y].kushal_down.distance + kushal_distance_array[old_include_x][old_include_y];
			kushal_from_array[x2][y2].x = old_include_x;
			kushal_from_array[x2][y2].y = old_include_y;
		}
		int x3 = kushal_board[old_include_x][old_include_y].kushal_left.end_x;
		int y3 = kushal_board[old_include_x][old_include_y].kushal_left.end_y;
		if (kushal_board[old_include_x][old_include_y].kushal_left.distance + kushal_distance_array[old_include_x][old_include_y] < kushal_distance_array[x3][y3])
		{
			kushal_distance_array[x3][y3] = kushal_board[old_include_x][old_include_y].kushal_left.distance + kushal_distance_array[old_include_x][old_include_y];
			kushal_from_array[x3][y3].x = old_include_x;
			kushal_from_array[x3][y3].y = old_include_y;
		}
		int x4 = kushal_board[old_include_x][old_include_y].kushal_right.end_x;
		int y4 = kushal_board[old_include_x][old_include_y].kushal_right.end_y;
		if (kushal_board[old_include_x][old_include_y].kushal_right.distance + kushal_distance_array[old_include_x][old_include_y] < kushal_distance_array[x4][y4])
		{
			kushal_distance_array[x4][y4] = kushal_board[old_include_x][old_include_y].kushal_right.distance + kushal_distance_array[old_include_x][old_include_y];
			kushal_from_array[x4][y4].x = old_include_x;
			kushal_from_array[x4][y4].y = old_include_y;
		}
		lowest = 999;
		new_include_x = 99;
		new_include_y = 99;
		for (int x = 0; x < kushal_length; x++)
		{
			for (int y = 0; y < kushal_width; y++)
			{
				if(kushal_include[x][y] == false)
				{
					if (lowest > kushal_distance_array[x][y])
					{
						lowest = kushal_distance_array[x][y];
						new_include_x = x;
						new_include_y = y;
					}
				}
			}
		}

		if (lowest == 999)
		{
			done = true;
			direction_counter = 0;

		}

		kushal_include[new_include_x][new_include_y] = true;
		old_include_x = new_include_x;
		old_include_y = new_include_y;
		if (new_include_x == e_x && new_include_y == e_y)
		{
			done = true;
			direction_counter = 0;
			while (kushal_from_array[new_include_x][new_include_y].x != -1)
			{
				if (new_include_y - kushal_from_array[new_include_x][new_include_y].y == 0)
				{
					if (new_include_x - kushal_from_array[new_include_x][new_include_y].x > 0)
					{
						kushal_direction_array[direction_counter] = 'R';
					}
					else
					{
						kushal_direction_array[direction_counter] = 'L';
					}
				}
				else if (new_include_y - kushal_from_array[new_include_x][new_include_y].y > 0)
				{
					kushal_direction_array[direction_counter] = 'D';
				}
				else
				{
					kushal_direction_array[direction_counter] = 'U';
				}
				direction_counter++;
				int temp1, temp2;
				temp1 = kushal_from_array[new_include_x][new_include_y].x;
				temp2 = kushal_from_array[new_include_x][new_include_y].y;
				new_include_x = temp1;
				new_include_y = temp2;
			}
		}
	}
	kushal_follow_directions();
}

void TurnRight()
{
	setMotorSpeed(RightTire, 0);
	setMotorSpeed(LeftTire, 0);
	int CurGyro = SensorValue[Gyro] + 84;
	setMotorSpeed(LeftTire, 25);
	setMotorSpeed(RightTire, -25);
	while(SensorValue[Gyro] < CurGyro)
	{
	}
	setMotorSpeed(LeftTire, 0);
	setMotorSpeed(RightTire, 0);
	sleep(100);
}

void TurnLeft()
{
	setMotorSpeed(RightTire, 0);
	setMotorSpeed(LeftTire, 0);
	int CurGyro = SensorValue[Gyro] - 84;
	setMotorSpeed(LeftTire, -25);
	setMotorSpeed(RightTire, 25);
	while(SensorValue[Gyro] > CurGyro)
	{
	}
	setMotorSpeed(LeftTire, 0);
	setMotorSpeed(RightTire, 0);
	sleep(100);
}

void FaceUp()
{
	setMotorSpeed(RightTire, 0);
	setMotorSpeed(LeftTire, 0);
	if (lastDirection == 'D')
	{
		TurnRight();
		TurnRight();
	}
	else if (lastDirection == 'R')
	{
		TurnLeft();
	}
	else if (lastDirection == 'L')
	{
		TurnRight();
	}

	lastDirection = 'U';
}

void FaceDown()
{
	setMotorSpeed(RightTire, 0);
	setMotorSpeed(LeftTire, 0);
	if (lastDirection == 'U')
	{
		TurnRight();
		TurnRight();
	}
	else if (lastDirection == 'L')
	{
		TurnLeft();
	}
	else if (lastDirection == 'R')
	{
		TurnRight();
	}

	lastDirection = 'D';
}

void FaceRight()
{
	setMotorSpeed(RightTire, 0);
	setMotorSpeed(LeftTire, 0);
	if (lastDirection == 'U')
	{
		TurnRight();

	}
	else if (lastDirection == 'D')
	{
		TurnLeft();
	}
	else if (lastDirection == 'L')
	{
		TurnRight();
		TurnRight();
	}

	lastDirection = 'R';
}

void FaceLeft()
{
	setMotorSpeed(RightTire, 0);
	setMotorSpeed(LeftTire, 0);
	if (lastDirection == 'D')
	{
		TurnRight();

	}
	else if (lastDirection == 'U')
	{
		TurnLeft();
	}
	else if (lastDirection == 'R')
	{
		TurnRight();
		TurnRight();
	}

	lastDirection = 'L';
}

void remove_down_road()
{
	displayTextLine(5,"road from %d,%d to %d, %d no longer exists!", current_x, current_y, current_x-1, current_y);
	sleep(1000);
	kushal_board[current_x][current_y].kushal_down.end_x = current_x;
	kushal_board[current_x][current_y].kushal_down.end_y = current_y;
	kushal_board[current_x][current_y ].kushal_down.distance = 99999;

	kushal_board[current_x][current_y + 1].kushal_up.end_x = current_x;
	kushal_board[current_x][current_y + 1].kushal_up.end_y = current_y + 1;
	kushal_board[current_x][current_y + 1].kushal_up.distance = 99999;
}

void remove_left_road()
{
	kushal_board[current_x][current_y].kushal_left.end_x = current_x;
	kushal_board[current_x][current_y].kushal_left.end_y = current_y;
	kushal_board[current_x][current_y].kushal_left.distance = 99999;

	kushal_board[current_x - 1][current_y].kushal_right.end_x = current_x - 1;
	kushal_board[current_x - 1][current_y].kushal_right.end_y = current_y;
	kushal_board[current_x - 1][current_y].kushal_right.distance = 99999;
}

void remove_up_road()
{
	kushal_board[current_x][current_y].kushal_up.end_x = current_x;
	kushal_board[current_x][current_y].kushal_up.end_y = current_y;
	kushal_board[current_x][current_y].kushal_up.distance = 99999;

	kushal_board[current_x][current_y - 1].kushal_down.end_x = current_x;
	kushal_board[current_x][current_y - 1].kushal_down.end_y = current_y - 1;
	kushal_board[current_x][current_y - 1].kushal_down.distance = 99999;
}

void remove_right_road()
{
	displayTextLine(7, "%d,%d", kushal_board[current_x][current_y].kushal_right.end_x, kushal_board[current_x][current_y].kushal_right.end_y);
	sleep(2000);
	kushal_board[current_x][current_y].kushal_right.end_x = current_x;
	kushal_board[current_x][current_y].kushal_right.end_y = current_y;
	kushal_board[current_x][current_y].kushal_right.distance = 99999;

	kushal_board[current_x + 1][current_y].kushal_left.end_x = current_x + 1;
	kushal_board[current_x + 1][current_y].kushal_left.end_y = current_y;
	kushal_board[current_x + 1][current_y].kushal_left.distance = 99999;
}

void check_for_red()
{
	if(SensorValue[LeftColor] == 5 && SensorValue[RightColor] == 5)
	{
		sleep(kushal_production_sleep_time);
		final_x = 0;
		final_y = 0;
		set_kushal_direction_array_to_input();
		Dijkstras(current_x, current_y, final_x, final_y);
		kushal_follow_directions();
	}
}

void GoBack()
{
	setMotorSpeed(LeftTire, 0);
	setMotorSpeed(RightTire, 0);
	setMotorSyncEncoder(LeftTire,RightTire,0,250,-30);
	while(getMotorRunning(LeftTire))
	{
	}
	sleep(kushal_production_sleep_time);
}

void go_to_random_destination()
{
	final_x = random(6);
	final_y = random(4);


	if (!have_we_visited_square[final_x][final_y])
	{
		Dijkstras(current_x, current_y, final_x, final_y);
	}
	else
		go_to_random_destination();
}

bool kushal_drive_in()
{
	setMotorSpeed(RightTire, 0);
	setMotorSpeed(LeftTire, 0);
	setMotorSyncEncoder(LeftTire,RightTire,0,700,40);
	while(getMotorRunning(LeftTire))
	{
		if(getTouchValue(Touch) == 1)
		{
			GoBack();
			return false;
		}

		if(SensorValue[LeftColor] < 2 && SensorValue[RightColor] > 2)
		{
			setMotorSpeed(RightTire, 0);
			setMotorSpeed(LeftTire, 0);
			setMotorSpeed(RightTire, 20);
			setMotorSpeed(LeftTire, -4);
			while(SensorValue[RightColor] > 10)
			{

			}
			setMotorSpeed(LeftTire, 0);
			setMotorSpeed(RightTire, 0);
		}
		else if(SensorValue[LeftColor] > 2 && SensorValue[RightColor] < 2)
		{
			setMotorSpeed(RightTire, 0);
			setMotorSpeed(LeftTire, 0);
			setMotorSpeed(LeftTire, 20);
			setMotorSpeed(RightTire, -4);
			while(SensorValue[LeftColor] > 2)
			{

			}
			setMotorSpeed(LeftTire, 0);
			setMotorSpeed(RightTire, 0);
		}
		else if(SensorValue[LeftColor] < 2 && SensorValue[RightColor] < 2)
		{
			setMotorSpeed(RightTire, 0);
			setMotorSpeed(LeftTire, 0);
		}

	}
	resetMotorEncoder(LeftTire);
	resetMotorEncoder(RightTire);
	setMotorSyncEncoder(LeftTire,RightTire,0,450,40);
	while(getMotorRunning(LeftTire))
	{
	}
	return true;
}

void kushal_follow_directions()
{
	// i helped you a lot and you should give me extra credit -- mitchel
	direction_counter = direction_counter_max - 1;
	while (direction_counter > -1)
	{
		if (kushal_direction_array[direction_counter] == 'D')
		{
			displayBigTextLine(3, "Down %d, %d, %d, %d", current_x, current_y, final_x, final_y);
			sleep(kushal_production_sleep_time);
			FaceDown();
			if(!kushal_drive_in())
			{
				sleep(kushal_production_sleep_time);
				remove_down_road();
				set_kushal_direction_array_to_input();
				Dijkstras(current_x, current_y, final_x, final_y);
				kushal_follow_directions();
			}
			else
			{
				current_y++;
				have_we_visited_square[current_x][current_y] = true;
				check_for_red();
			}
		}
		else if (kushal_direction_array[direction_counter] == 'U')
		{
			displayBigTextLine(3, "Up %d, %d, %d, %d", current_x, current_y, final_x, final_y);
			sleep(kushal_production_sleep_time);
			FaceUp();
			if(!kushal_drive_in())
			{
				sleep(kushal_production_sleep_time);
				remove_up_road();
				set_kushal_direction_array_to_input();
				Dijkstras(current_x, current_y, final_x, final_y);
				kushal_follow_directions();
			}
			else
			{
				current_y--;
				have_we_visited_square[current_x][current_y] = true;
				check_for_red();
			}
		}
		else if (kushal_direction_array[direction_counter] == 'L')
		{
			displayBigTextLine(3, "Left %d, %d, %d, %d", current_x, current_y, final_x, final_y);
			sleep(kushal_production_sleep_time);
			FaceLeft();
			if(!kushal_drive_in())
			{
				sleep(kushal_production_sleep_time);
				remove_left_road();
				set_kushal_direction_array_to_input();
				Dijkstras(current_x, current_y, final_x, final_y);
				kushal_follow_directions();
				direction_counter = 0;
			}
			else
			{
				current_x--;
				have_we_visited_square[current_x][current_y] = true;
				check_for_red();
			}
		}
		if (kushal_direction_array[direction_counter] == 'R')
		{
			displayBigTextLine(3, "Right %d, %d, %d, %d", current_x, current_y, final_x, final_y);
			sleep(kushal_production_sleep_time);
			FaceRight();
			if(!kushal_drive_in())
			{
				sleep(kushal_production_sleep_time);
				remove_right_road();
				set_kushal_direction_array_to_input();
				Dijkstras(current_x, current_y, final_x, final_y);
				kushal_follow_directions();
			}
			else
			{
				current_x++;
				have_we_visited_square[current_x][current_y] = true;
				check_for_red();
			}
		}


		direction_counter--;
	}

	if (current_x == 0 && current_y == 0)
		{
			return;
		}
		else { go_to_random_destination(); }
}
	task main()
	{
		lastDirection = 'U';
		sleep(kushal_production_sleep_time);
		current_x = current_y = final_x = final_y = 0;

		bool kushal_moves[updownleftright];

		for (int i = 0; i < kushal_length; i++)
		{
			for (int j = 0; j < kushal_width; j++)
			{
				//current_x = i;
				//current_y = j;
				have_we_visited_square[i][j] = false;

				kushal_board[i][j].kushal_up.start_x = i;
				kushal_board[i][j].kushal_up.start_y = j;
				kushal_board[i][j].kushal_up.end_x = i;
				kushal_board[i][j].kushal_up.end_y = j;
				kushal_board[i][j].kushal_up.distance = 1;

				kushal_board[i][j].kushal_down.start_x = i;
				kushal_board[i][j].kushal_down.start_y = j;
				kushal_board[i][j].kushal_down.end_x = i;
				kushal_board[i][j].kushal_down.end_y = j;
				kushal_board[i][j].kushal_down.distance = 1;

				kushal_board[i][j].kushal_left.start_x = i;
				kushal_board[i][j].kushal_left.start_y = j;
				kushal_board[i][j].kushal_left.end_x = i;
				kushal_board[i][j].kushal_left.end_y = j;
				kushal_board[i][j].kushal_left.distance = 1;

				kushal_board[i][j].kushal_right.start_x = i;
				kushal_board[i][j].kushal_right.start_y = j;
				kushal_board[i][j].kushal_right.end_x = i;
				kushal_board[i][j].kushal_right.end_y = j;
				kushal_board[i][j].kushal_right.distance = 1;
			}
		}

		for (int i = 0; i < kushal_length; i++)
		{
			for (int j = 0; j < kushal_width; j++)
			{
				for (int apple = 0; apple < updownleftright; apple++)
				{
					kushal_moves[apple] = true;
				}
				if (j == 0)
				{
					kushal_moves[0] = false;
				}
				else if (j == 4)
				{
					kushal_moves[1] = false;
				}
				if (i == 0)
				{
					kushal_moves[2] = false;
				}
				else if (i == 6)
				{
					kushal_moves[3] = false;
				}
				if (kushal_moves[0] == true)
				{
					// can go up
					kushal_board[i][j].kushal_up.end_y = j - 1;
				}
				if (kushal_moves[1] == true)
				{
					// can go down
					kushal_board[i][j].kushal_down.end_y = j + 1;
				}
				if (kushal_moves[2] == true)
				{
					// can go left
					kushal_board[i][j].kushal_left.end_x = i - 1;
				}
				if (kushal_moves[3] == true)
				{
					// can go up
					kushal_board[i][j].kushal_right.end_x = i + 1;
				}
			}
		}
		final_x = 4;
		final_y = 2;
		// we have our boards built completely
		Dijkstras(0, 0, 4, 2);
		sleep(kushal_production_sleep_time);
	}
