#pragma config(Sensor, S2,     LeftColor,      sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S1,     RightColor,     sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S3,     Gyro,           sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S4,     Touch,          sensorEV3_Touch)
#pragma config(Motor,  motorB,          LeftTire,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          RightTire,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int current_x, current_y, final_x, final_y;

const int kushal_length = 7;
const int kushal_width = 5;
const int updownleftright = 4;
const int kushal_production_sleep_time = 100;

bool have_we_visited_square[kushal_length][kushal_width];

struct kushal_road{
	int start_x, start_y, end_x, end_y, distance;
};

struct kushal_square{
	kushal_road kushal_up, kushal_down, kushal_left, kushal_right;
	int location_x, location_y;
};

kushal_square kushal_board[kushal_length][kushal_width];

task main()
{
	sleep(kushal_production_sleep_time);
	current_x = current_y = final_x = final_y = 0;

	bool kushal_moves[updownleftright];

	for (int i = 0; i < kushal_length; i++)
	{
		for (int j = 0; j < kushal_width; j++)
		{
			current_x = i;
			current_y = j;
			have_we_visited_square[i][j] = false;

			kushal_board[i][j].kushal_up.start_x = i;
			kushal_board[i][j].kushal_up.start_y = j;
			kushal_board[i][j].kushal_up.end_x = i;
			kushal_board[i][j].kushal_up.end_y = j;
			kushal_board[i][j].kushal_up.distance = 1;

			kushal_board[i][j].kushal_down.start_x = i;
			kushal_board[i][j].kushal_down.start_y = j;
			kushal_board[i][j].kushal_down.end_x = i;
			kushal_board[i][j].kushal_down.end_y = j;
			kushal_board[i][j].kushal_down.distance = 1;

			kushal_board[i][j].kushal_left.start_x = i;
			kushal_board[i][j].kushal_left.start_y = j;
			kushal_board[i][j].kushal_left.end_x = i;
			kushal_board[i][j].kushal_left.end_y = j;
			kushal_board[i][j].kushal_left.distance = 1;

			kushal_board[i][j].kushal_right.start_x = i;
			kushal_board[i][j].kushal_right.start_y = j;
			kushal_board[i][j].kushal_right.end_x = i;
			kushal_board[i][j].kushal_right.end_y = j;
			kushal_board[i][j].kushal_right.distance = 1;
		}
	}

	for (int i = 0; i < kushal_length; i++)
	{
		for (int j = 0; j < kushal_width; j++)
		{
			for (int apple = 0; apple < updownleftright; apple++)
			{
				kushal_moves[apple] = true;
			}
			if (j == 0)
			{
				kushal_moves[0] = false;
			}
			else if (j == 4)
			{
				kushal_moves[1] = false;
			}
			if (i == 0)
			{
				kushal_moves[2] = false;
			}
			else if (i == 6)
			{
				kushal_moves[3] = false;
			}
			if (kushal_moves[0] == true)
			{
				// can go up
				kushal_board[i][j].kushal_up.end_y = j + 1;
			}
			if (kushal_moves[1] == true)
			{
				// can go down
				kushal_board[i][j].kushal_down.end_y = j - 1;
			}
			if (kushal_moves[2] == true)
			{
				// can go left
				kushal_board[i][j].kushal_left.end_x = i - 1;
			}
			if (kushal_moves[3] == true)
			{
				// can go up
				kushal_board[i][j].kushal_right.end_x = i + 1;
			}
		}
	}
	// we have our boards built completely
}
