#pragma config(Sensor, S1,     LeftColorSensor, sensorEV3_Color)
#pragma config(Sensor, S2,     RightColorSensor, sensorEV3_Color)
#pragma config(Sensor, S3,     GyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S4,     TouchSensor,    sensorEV3_Touch)
#pragma config(Motor,  motorB,          LeftTire,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          RightTire,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int KSoundVolume = 5;

int KForwardSpeed = 20;
int KForwardRotate = 180;
int KForwardRatio = 0;
int KTurnSpeed = 20;
int KDebugTimeout = 5000;
const int KTrayLength = 7;
const int KTrayWidth = 5;

int KushalTray[KTrayLength][KTrayWidth];

void PrintStats()
{
	displayBigTextLine(4, "welcome, kus");
	short lightSensorValue;
	lightSensorValue = SensorValue(LightSensor);
	displayBigTextLine(6, "%d", lightSensorValue);
	float colorSensorValue;
	colorSensorValue = getColorReflected(ColorSensor);
	displayBigTextLine(8, "%d", colorSensorValue);
	resetMotorEncoder(LeftTire);
	resetMotorEncoder(RightTire);
	sleep(KDebugTimeout);
}

void InitializeTray(int InitialValue)
{
	for (int i = 0; i < KTrayLength; i++)
	{
		for (int j = 0; j < KTrayWidth; j++)
		{
			KushalTray[i][j] = InitialValue;
		}
	}
}

void GoForward()
{
	sleep(KDebugTimeout);
	setMotorSyncEncoder(LeftTire, RightTire, KForwardRatio, KForwardRotate, KForwardSpeed);
}

bool ShouldGoLeft()
{
	if(SensorValue(LightSensor) > 30 && SensorValue(ColorSensor) < 5){return true;} else {return false;}
}

bool ShouldGoRight()
{
	if(SensorValue(LightSensor) < 30 && SensorValue(ColorSensor) > 5){return true;} else {return false;}
}

task main()
{
	setSoundVolume(KSoundVolume);
	InitializeTray(0);
	while(true)
	{
		PrintStats();
		while(ShouldGoLeft())
		{
			displayBigTextLine(10, "go left");
			motor[LeftTire] = -KTurnSpeed;
			motor[RightTire] = KTurnSpeed;
		}
		while(ShouldGoRight())
		{
			displayBigTextLine(10, "go right");
			motor[LeftTire] = KTurnSpeed;
			motor[RightTire] = -KTurnSpeed;
		}
		while(!ShouldGoRight() && !ShouldGoLeft())
		{
			displayBigTextLine(10, "go straight");
			motor[LeftTire] = KForwardSpeed;
			motor[RightTire] = KForwardSpeed;
		}
	}
}
