#pragma config(Sensor, S1,     ColorSensor,    sensorEV3_Color)
#pragma config(Sensor, S2,     LightSensor,    sensorLightActive)
#pragma config(Sensor, S3,     GyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S4,     UltrasonicSensor, sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          leftTire,      tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          RightTire,     tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorA,          arm,           tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int RotateSpeed = 20;
int LightSensorThreshold = 10;
int ColorSensorThreshold = 30;

void DisplaySensorData()
{
	int iColor = getColorReflected(ColorSensor);
	displayTextLine(2, "%d", iColor);
	int iLight = SensorValue(LightSensor);
	displayTextLine(4, "%d", iLight);
	int iGyro = getGyroDegrees(GyroSensor);
	displayTextLine(6, "Gyro %d", getGyroDegrees(GyroSensor));
	int iUltrasonic = getUSDistance(UltrasonicSensor);
	iUltrasonic = iUltrasonic % 360;
	displayTextLine(8, "%d", iUltrasonic);
	displayTextLine(10, "canary");
}

void RotateLeft()
{
	motor[leftTire] = -RotateSpeed;
	motor[RightTire] = RotateSpeed;
	sleep(1000);
}

void RotateRight()
{
	setMotorSyncEncoder(motorC, motorB, 1, 1, RotateSpeed);
}

void dontstop()
{
	motor[leftTire] = 0;
	motor[RightTire] = 0;
}

task main()
{
	resetGyro(GyroSensor);
	while((getGyroDegrees(GyroSensor) % 360) > -90)
	{
		RotateRight();
		DisplaySensorData();
	}
}
