#pragma config(Sensor, S1,     ColorSensor,    sensorEV3_Color)
#pragma config(Sensor, S2,     LightSensor,    sensorLightActive)
#pragma config(Sensor, S3,     GyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S4,     UltrasonicSensor, sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          leftTire,      tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          RightTire,     tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorA,          arm,           tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void DisplaySensorData()
{
	int iColor = getColorReflected(ColorSensor);
	displayTextLine(2, "%d", iColor);
	int iLight = SensorValue(LightSensor);
	displayTextLine(4, "%d", iLight);
	int iGyro = getGyroDegrees(GyroSensor);
	displayTextLine(6, "%d", iGyro);
	int iUltrasonic = getUSDistance(UltrasonicSensor);
	iUltrasonic = iUltrasonic % 360;
	displayTextLine(8, "%d", iUltrasonic);
}

void RotateLeft()
{
	motor[leftTire] = -20;
	motor[RightTire] = 20;
}

task main()
{
	resetGyro(GyroSensor);
	while(true)
	{
		RotateLeft();
		DisplaySensorData();
	}
}
