#pragma config(Sensor, S1,     ColorSensor,    sensorEV3_Color)
#pragma config(Sensor, S4,     UltrasonicSensor, sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          Arm,           tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          LeftTire,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          RightTire,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int distance = 0;
int GoBackLeftTire = 0;
int GoBackRightTire = 0;
int GoForwardLeftTire = 0;
int GoForwardRightTire = 0;
int SweepAngle = 80;
int SweepSpeed = 40;

void GoForwardSlowly()
{
	GoForwardLeftTire = 0;
	GoForwardRightTire = 0;
	if (distance > 10 || distance == 255)
	{
		setMotorSyncEncoder(LeftTire, RightTire, 0, 360, 20);
	}
}

void GoBackwardSlowly()
{
	GoBackLeftTire = 0;
	GoBackRightTire = 0;
	if ((distance > 10 || distance == 255))
	{
		setMotorSyncEncoder(LeftTire, RightTire, 0, 360, 20);
	}
}

task main()
{
	resetMotorEncoder(LeftTire);
	resetMotorEncoder(RightTire);
	while(true)
	{
		distance = getUSDistance(S4);
		displayBigTextLine(6, "%d", distance);
		displayBigTextLine(10, "%d %d %d %d", GoBackLeftTire, GoBackRightTire, GoForwardLeftTire, GoForwardRightTire);
		setMotorSyncEncoder(LeftTire, RightTire, 0, 360, 90);
		motor[LeftTire]=90;
		motor[RightTire]=90;
		while(SensorValue(ColorSensor) < 14 && (distance > 10 || distance == 255) || (GoBackLeftTire > 5 && GoBackRightTire > 5 && GoForwardLeftTire == 0 && GoForwardRightTire == 0))
		{
			GoBackLeftTire = 0;
			GoBackRightTire = 0;
			GoForwardLeftTire = 0;
			GoForwardRightTire = 0;
			setMotorSyncEncoder(LeftTire, RightTire, 0, 1000, 90);
		}
		setMotorSyncEncoder(LeftTire, RightTire, 0, 0, 0);
		if (GoForwardLeftTire < 5)
		{
			moveMotorTarget(LeftTire, SweepAngle, SweepSpeed);
			GoForwardLeftTire++;
		}
		else
		{
			GoBackwardSlowly();
		}
		while (getMotorMoving(LeftTire) && GoBackRightTire < 5)
		{
			if (SensorValue(ColorSensor) < 14 && GoBackLeftTire < 5)
			{
				break;
			}
		}
		if (GoBackLeftTire < 5)
		{
			moveMotorTarget(LeftTire, SweepAngle, -SweepSpeed);
			GoBackLeftTire++;
		}
		else
		{
			GoBackwardSlowly();
		}
		while (getMotorMoving(LeftTire))
		{
			if (SensorValue(ColorSensor) < 14)
			{
				break;
			}
		}
		if (GoForwardLeftTire < 5)
		{
			moveMotorTarget(RightTire, SweepAngle, SweepSpeed);
			GoForwardRightTire++;
		}
		else
		{
			GoForwardSlowly();
		}
		while (getMotorMoving(RightTire) && GoBackRightTire < 5)
		{
			if (SensorValue(ColorSensor) < 14)
			{
				break;
			}
		}
		if (GoBackRightTire < 5)
		{
			moveMotorTarget(RightTire, SweepAngle, -SweepSpeed);
			GoBackRightTire++;
		}
		else
		{
			GoForwardSlowly();
		}
		while (getMotorMoving(RightTire))
		{
			if (SensorValue(ColorSensor) < 14)
			{
				break;
			}
		}
	}
};
