#pragma config(Sensor, S1,     ColorSensor,    sensorEV3_Color)
#pragma config(Sensor, S3,     LightSensor,    sensorLightActive)
#pragma config(Motor,  motorB,          LeftTire,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          RightTire,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int iStopLightSensor = 35;
int iStopColorSensor = 15;
int iRotateAngle = 150;
int iRotateSpeed = 25;
int sleepTime = 5000;
task main()
{
	resetMotorEncoder(LeftTire);
	resetMotorEncoder(RightTire);
	while(true)
	{
		resetMotorEncoder(LeftTire);
		resetMotorEncoder(RightTire);
		displayBigTextLine(4, "welcome, kus");
		short lightSensorValue;
		lightSensorValue = SensorValue(LightSensor);
		displayBigTextLine(6, "%d", lightSensorValue);
		float colorSensorValue;
		colorSensorValue = getColorReflected(ColorSensor);
		displayBigTextLine(8, "%d", colorSensorValue);
		if(getColorReflected(ColorSensor) >= iStopColorSensor && SensorValue(LightSensor) >= iStopLightSensor)
		{
			displayBigTextLine(10, "go straight");
			sleep(sleepTime);
			setMotorSyncEncoder(LeftTire, RightTire, 0, 360, 30);
			//motor[LeftTire] = iRotateSpeed * 2;
			//motor[RightTire] = iRotateSpeed * 2;
			while (getMotorMoving(LeftTire) || getMotorMoving(RightTire))
			{
				if (SensorValue(ColorSensor) < iStopColorSensor || SensorValue(LightSensor) < iStopLightSensor)
				{
					// My right sensor found white stop moving
					motor[LeftTire] = 0;
					motor[RightTire] = 0;
					break;
				}
			}
		}
		if(getColorReflected(ColorSensor) < iStopColorSensor)
		{
			setMotorTarget(LeftTire, iRotateAngle, iRotateSpeed);
			while (getMotorMoving(LeftTire))
			{
				if (SensorValue(ColorSensor) > iStopColorSensor)
				{
					// My right sensor found white stop moving
				displayBigTextLine(10, "go left");
					sleep(sleepTime);
					motor[LeftTire] = 0;
					break;
				}
			}
		}
		if(SensorValue(LightSensor) < iStopLightSensor)
		{
			setMotorTarget(RightTire, iRotateAngle, iRotateSpeed);
			while (getMotorMoving(RightTire))
			{
				if (SensorValue(LightSensor) > iStopLightSensor)
				{
					displayBigTextLine(10, "go right");
					sleep(sleepTime);
					motor[RightTire] = 0;
					break;
				}
			}
		}
	}
};
