#pragma config(Sensor, S1,     ColorSensor,    sensorEV3_Color)
#pragma config(Sensor, S4,     UltrasonicSensor, sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          Arm,           tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          LeftTire,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          RightTire,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//void goRight()
//{
//	resetMotorEncoder(LeftTire);
//	resetMotorEncoder(RightTire);

//	while(true)
//	{
//		motor[LeftTire]=90;
//		motor[RightTire]=90;
//		while(SensorValue(ColorSensor) < 20){}
//		motor[LeftTire] = 0;
//		motor[RightTire] = 0;
//		while(SensorValue(ColorSensor) > 18)
//		{
//			motor[LeftTire] = 20;
//			motor[RightTire] = -20;
//		}
//	}
//}

//void goLeft()
//{
//	resetMotorEncoder(LeftTire);
//	resetMotorEncoder(RightTire);

//	while(true)
//	{
//		motor[LeftTire]=90;
//		motor[RightTire]=90;
//		while(SensorValue(ColorSensor) < 20){}
//		motor[LeftTire] = 0;
//		motor[RightTire] = 0;
//		while(SensorValue(ColorSensor) > 18)
//		{
//			motor[RightTire] = 20;
//			motor[LeftTire] = -20;
//		}
//	}
//}

task main()
{
	resetMotorEncoder(LeftTire);
	resetMotorEncoder(RightTire);

	while(true)
	{
		motor[LeftTire]=90;
		motor[RightTire]=90;
		while(SensorValue(ColorSensor) < 20){}
		motor[LeftTire] = 0;
		motor[RightTire] = 0;
		while(SensorValue(ColorSensor) > 18)
		{
			moveMotorTarget(LeftTire, 60, 60);
		}
	}
};
