#pragma config(Sensor, S1,     ColorSensor,    sensorEV3_Color)
#pragma config(Sensor, S4,     UltrasonicSensor, sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          Arm,           tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          LeftTire,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          RightTire,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	resetMotorEncoder(LeftTire);
	resetMotorEncoder(RightTire);

	motor[LeftTire]=20;
	motor[RightTire]=20;
	while(SensorValue(ColorSensor) < 20)
	{

	}
	motor[LeftTire] = 0;
	motor[RightTire] = 0;
	sleep(500);
	while(SensorValue(ColorSensor) > 18)
	{
		motor[LeftTire] = 10;
		motor[RightTire] = -10;
	}
	motor[LeftTire]=20;
	motor[RightTire]=20;
	while(SensorValue(ColorSensor) < 20)
	{

	}
	motor[LeftTire]=20;
	motor[RightTire]=20;
	//while(true)
	//{
	//	int x = SensorValue(ColorSensor);
	//	displayBigTextLine(2, "Color value: %d", x);
	//}
};
